frameworkWeb/config/routes.rb
Rails.application.routes.draw do
  get 'control_users/index'
  get 'control_users/new'

  post 'control_users', to: 'control_users#create', as: "new_user"

  delete '/alunos_departamentos/:id', to: 'alunos_departamentos#destroy', as: 'delete_aluno_departamento'

  devise_for :users

  resources :control_users
  resources :matriculas
  resources :alunos
  resources :estados
  resources :departamentos
  resources :alunos_departamentos
  
  root 'main#index'
  get 'inicio' => 'main#index'
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

frameworkWeb/app/models/departamento.rb
class Departamento < ApplicationRecord
    has_and_belongs_to_many :alunos, dependent: :destroy

end

frameworkWeb/app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /departamentos or /departamentos.json
  def index
    @departamentos = Departamento.all
    
  end

  # GET /departamentos/1 or /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos or /departamentos.json
  def create
    if(current_user.role == "admin")
      @departamento = Departamento.new(departamento_params)

      respond_to do |format|
        if @departamento.save
          format.html { redirect_to departamento_url(@departamento), notice: "Departamento was successfully created." }
          format.json { render :show, status: :created, location: @departamento }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @departamento.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to matriculas_path, notice: "Admin only"
    end
  end

  # PATCH/PUT /departamentos/1 or /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to departamento_url(@departamento), notice: "Departamento was successfully updated." }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1 or /departamentos/1.json
  def destroy
    @departamento.destroy

    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: "Departamento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.require(:departamento).permit(:nome, :campus)
    end
end

frameworkWeb/app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

frameworkWeb/app/views/departamentos/_departamento.html.erb
<div id="<%= dom_id departamento %>" class="show">
  <p>
    <strong>Nome:</strong>
    <%= departamento.nome %>
  </p>

  <p>
    <strong>Campus:</strong>
    <%= departamento.campus %>
  </p>

</div>

frameworkWeb/app/views/departamentos/_form.html.erb
<%= form_with(model: departamento) do |form| %>
  <% if departamento.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
        <% departamento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="formEdit">
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div class="formEdit">
    <%= form.label :campus, style: "display: block" %>
    <%= form.text_field :campus %>
  </div>

  <div class="formEdit">
    <%= form.submit %>
  </div>
<% end %>

frameworkWeb/app/views/departamentos/_modal.html.erb
<div id="opestado<%= departamento.id %>" style="display: none" class="allModal">
    <div class="textModal">
    <span>
        Nome:
        <%= departamento.nome %>
        </span>
        <span>
        Campus:
        <%= departamento.campus %>
        </span>
    </div>
    <% if current_user.role == 'admin' %>
        <div class=operaModal>
            <span>
                <%= link_to "Edit this departamento", edit_departamento_path(departamento) %>
            </span>
            <span>
                <%= button_to "Destroy this departamento", departamento, method: :delete %>
            </span>
        </div>
    <% end %>
</div>

frameworkWeb/app/views/departamentos/_table.html.erb
<tr id="estado<%= departamento.id %>" data-controller="fade" data-action="click->fade#fade_in">
  <td>
    <%= departamento.id %>
  </td>
  <td>
    <%= departamento.nome %>
  </td>
  <td>
    <%= departamento.campus %>
  </td>
</tr>

frameworkWeb/app/views/departamentos/edit.html.erb
<h1>Editing departamento</h1>

<%= render "form", departamento: @departamento %>

<br>

<div class="edit">
  <%= link_to "Show this departamento", @departamento %> |
  <%= link_to "Back to departamentos", departamentos_path %>
</div>

frameworkWeb/app/views/departamentos/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Departamentos</h1>

<div id="link-top">
  <%= link_to  "Home", root_path %>
</div>

<div id="departamentos">
  <table>
    <thead>
      <tr>
      <th>Id</th>
        <th>Nome</th>
        <th>Campus</th>
      </tr>
    </thead>
    <tbody>
      <% @departamentos.each do |departamento| %>
        <%= render "table",  departamento: departamento %> 
      <% end %>
    </tbody>
  </table>
</div>

<% if current_user.role == 'admin' %>
<div id="link-bottom">
  <%= link_to "New departamento", new_departamento_path %>
</div>
<% end  %>

<div id="modal" class="modal">
  <div class="modal-content">
    <span id="close-modal" class="close" data-controller="fade" data-action="click->fade#fade_out">&times;</span>
      <% @departamentos.each do |departamento| %>
        <%= render "modal",  departamento: departamento %> 
      <% end %>
  </div>
</div>

frameworkWeb/app/views/departamentos/new.html.erb
<h1>New departamento</h1>

<div class="new_user">
<%= render "form", departamento: @departamento %>

<br>

<div class="showLinksBlack">
  <%= link_to "Back to departamentos", departamentos_path %>
</div>
</div>

frameworkWeb/app/views/departamentos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @departamento %>

<div class="showLinks">
  <%= link_to "Edit this departamento", edit_departamento_path(@departamento) %> |
  <%= link_to "Back to departamentos", departamentos_path %>

  <%= button_to "Destroy this departamento", @departamento, method: :delete %>
</div>