frameworkWeb/config/routes.rb
Rails.application.routes.draw do
  get 'control_users/index'
  get 'control_users/new'

  post 'control_users', to: 'control_users#create', as: "new_user"

  delete '/alunos_departamentos/:id', to: 'alunos_departamentos#destroy', as: 'delete_aluno_departamento'

  devise_for :users

  resources :control_users
  resources :matriculas
  resources :alunos
  resources :estados
  resources :departamentos
  resources :alunos_departamentos
  
  root 'main#index'
  get 'inicio' => 'main#index'
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

frameworkWeb/app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users=User.all
    @newUser=User.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to control_users_index_path, notice: "Criado com sucesso"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to control_users_index_path
    else
      redirect_to control_users_index_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end
end

frameworkWeb/app/helpers/control_users_helper.rb
module ControlUsersHelper
end

frameworkWeb/app/views/control_users/_modal.html.erb
<div id="opestado<%= user.id %>" style="display: none" class="allModal">
    <div class="textModal">
        <span>
            Email:
            <%= user.email %>
        </span>
        <span>
            Role:
            <%= user.role %>
        </span>
        
        <% if current_user.role == 'admin' %>
            <div class=operaModal>
                <span>
                    <%= button_to "Destroy this user", control_user_path(user), method: :delete %>
                </span>
            </div>
        <% end %>
        
    

    </div>
</div>

frameworkWeb/app/views/control_users/_table.html.erb
<tr id="estado<%= user.id %>" data-controller="fade" data-action="click->fade#fade_in">
  <td>
    <%= user.email %>
  </td>
  <td>
    <%= user.role %>
  </td>
</tr>

frameworkWeb/app/views/control_users/index.html.erb
<h1>Users</h1>
<div id="link-top">
<%= link_to  "Home", root_path %>
</div>
<div id="users">
  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Role</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <%= render "table",  user: user %> 
      <% end %>
    </tbody>
  </table>
</div>

<div id="link-bottom">
<%= link_to  "new_user", control_users_new_path %>
</div>

<div id="modal" class="modal">
  <div class="modal-content">
    <span id="close-modal" class="close" data-controller="fade" data-action="click->fade#fade_out">&times;</span>
      <% @users.each do |user| %>
        <%= render "modal",  user: user %> 
      <% end %>
  </div>
</div>

frameworkWeb/app/views/control_users/new.html.erb
<h1>New User</h1>

<%= form_for(User.new, url: new_user_path) do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email, autofocus: true %>

  <%= f.label :password %>
  <%= f.password_field :password, autocomplete: "new-password" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, autocomplete: "new-password" %>

  <%= f.label :role %>
  <%= f.select :role, options_for_select(['admin', 'normal_user']) %>


  <%= f.submit "Create User" %>
  <div class="showLinksBlack">
    <%= link_to "Back to users", control_users_path %>
  </div>
<% end %>