frameworkWeb/config/routes.rb
Rails.application.routes.draw do
  get 'control_users/index'
  get 'control_users/new'

  post 'control_users', to: 'control_users#create', as: "new_user"

  delete '/alunos_departamentos/:id', to: 'alunos_departamentos#destroy', as: 'delete_aluno_departamento'

  devise_for :users

  resources :control_users
  resources :matriculas
  resources :alunos
  resources :estados
  resources :departamentos
  resources :alunos_departamentos
  
  root 'main#index'
  get 'inicio' => 'main#index'
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

frameworkWeb/app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        @users = User.all
                
        if current_user == nil
            @userAtual=""
        else
            if current_user.role == "admin"
                @userAtual="admin"
            else
                @userAtual="padrao"
            end
        end
    end
end

frameworkWeb/app/helpers/main_helper.rb
module MainHelper
end

frameworkWeb/app/views/main/index.html.erb
<div id="main-login">
    <h1>Trabalho 4</h1>

    <ul>
        <% if user_signed_in? %>
            <% if current_user.role == 'normal_user' %>
                <li><strong>Usuário:</strong> <%= current_user.email %></li>
            <% else %>
                <li><strong>Admin:</strong> <%= current_user.email %></li>
            <% end %>
            <li><%= link_to  "Sign out", destroy_user_session_path, class: "main-sign" %></li>
        <% else %>
            <li><%= link_to  "Sign in", new_user_session_path, class: "main-sign" %></li>
            <li><%= link_to  "Sign up", new_user_registration_path, class: "main-sign" %></li>
        <% end  %>
    </ul>
    <br/>
</div>

<div id="main-links">
    <h3>Tabelas disponíveis</h3>
    <%= link_to  "Departamentos", departamentos_path, class: "main-links" %>
    <%= link_to  "Estados", estados_path, class: "main-links" %>
    <%= link_to  "Alunos", alunos_path, class: "main-links" %>
    <%= link_to  "Matriculas", matriculas_path, class: "main-links" %>
    <%= link_to  "Alunos Departamentos", alunos_departamentos_path, class: "main-links" %>
    <% if @userAtual == "admin" %>
        <%= link_to  "Users", control_users_index_path, class: "main-links" %>
    <% end %>
</div>

<div data-controller="fade" data-action="click->fade#fade_in"></div>